# Generated by Django 2.0.6 on 2018-06-15 13:03

from django.db import migrations, models
import django.utils.timezone
import easy_thumbnails.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=90, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=90, verbose_name='Прізвище')),
                ('information', tinymce.models.HTMLField(blank=True, max_length=256, verbose_name='Інформація')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='photos/teachers', verbose_name='Світлина')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name_plural': 'posts',
                'ordering': ('-pub_date',),
            },
        ),
    ]
