# Generated by Django 2.0.6 on 2018-07-04 09:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('theteachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='information',
            field=tinymce.models.HTMLField(blank=True, max_length=500, verbose_name='Інформація'),
        ),
    ]
