# Generated by Django 2.0.6 on 2018-07-17 19:39

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theteachers', '0002_auto_20180704_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='placeholder-avatar.jpg', upload_to='photos/teachers', verbose_name='Світлина'),
        ),
    ]
