# Generated by Django 2.0.6 on 2018-07-18 07:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('theteachers', '0003_auto_20180717_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='first_name_pl',
            field=models.CharField(blank=True, max_length=90, verbose_name="Ім'я польською"),
        ),
        migrations.AddField(
            model_name='teacher',
            name='information_pl',
            field=tinymce.models.HTMLField(blank=True, max_length=500, verbose_name='Інформація польською'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name_pl',
            field=models.CharField(blank=True, max_length=90, verbose_name='Прізвище польською'),
        ),
    ]
