# Generated by Django 2.0.6 on 2018-07-17 19:39

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180615_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='placeholder-post.jpg', upload_to='photos/blog', verbose_name='Світлина'),
        ),
    ]
