# Generated by Django 2.0.6 on 2018-07-18 07:18

from django.db import migrations, models
import easy_thumbnails.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180717_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_pl',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст польською'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_pl',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='placeholder-post.jpg', upload_to='photos/blog', verbose_name='Світлина польською'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_descr_pl',
            field=tinymce.models.HTMLField(blank=True, max_length=256, verbose_name='Короткий опис польсьокю'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_pl',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок польською'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='Заголовок'),
        ),
    ]
